# Generated by Django 5.2.5 on 2025-11-30 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendaOnlineApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='foto_referencia',
        ),
        migrations.AddField(
            model_name='pedido',
            name='foto_referencia1',
            field=models.ImageField(null=True, upload_to='pedidos'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='foto_referencia2',
            field=models.ImageField(blank=True, null=True, upload_to='pedidos'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='foto_referencia3',
            field=models.ImageField(blank=True, null=True, upload_to='pedidos'),
        ),
    ]
